package com.devbits.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AuthorityId generated by hbm2java
 */
@Embeddable
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AuthorityId implements java.io.Serializable {

	private static final long serialVersionUID = -561316693429390664L;
	
	@Column(name = "username", nullable = false)
	private String username;
	@Column(name = "role", nullable = false)
	private String role;

}
